# Generated by Django 4.0 on 2021-12-07 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=9)),
                ('empresa', models.CharField(max_length=40)),
                ('descricao', models.TextField(blank=True)),
                ('email', models.CharField(max_length=40)),
                ('novo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
