# Generated by Django 4.0 on 2021-12-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
